-- ============================================================================
-- Database Configuration / Andmebaasi Konfiguratsioon
-- ============================================================================
-- This script creates the college database in PostgreSQL.
-- See skript loob kolledži andmebaasi PostgreSQL-is.
--
-- SECURITY WARNING / TURVALISUSE HOIATUS:
-- DO NOT use the default 'postgres' user for application access in production!
-- ÄRA kasuta vaikimisi 'postgres' kasutajat rakenduse juurdepääsuks toodangus!
--
-- The postgres user has full privileges including DROP DATABASE and DROP TABLE.
-- For application use, create a limited-privilege user that can only:
--   - SELECT, INSERT, UPDATE, DELETE on tables
--   - Cannot DROP tables or databases
--   - Cannot create new users
--
-- Root kasutajal on täielikud õigused, sealhulgas DROP DATABASE ja DROP TABLE.
-- Rakenduse kasutamiseks loo piiratud õigustega kasutaja, kes saab ainult:
--   - SELECT, INSERT, UPDATE, DELETE tabelitel
--   - Ei saa DROP-ida tabeleid ega andmebaase
--   - Ei saa luua uusi kasutajaid
--
-- See the SETUP_GUIDE.md for instructions on creating a secure database user.
-- Vaata SETUP_GUIDE.md juhiseid turvalise andmebaasi kasutaja loomiseks.
-- ============================================================================

-- Create the database / Loo andmebaas
CREATE DATABASE college_db;

-- Connect to the database / Ühendu andmebaasiga
-- In psql, run: \c college_db

-- ============================================================================
-- OPTIONAL: Create a limited-privilege user for application use
-- VALIKULINE: Loo piiratud õigustega kasutaja rakenduse kasutamiseks
-- ============================================================================
-- Uncomment and customize these lines to create a secure application user:
-- Eemalda kommentaar ja kohanda neid ridu turvalise rakenduse kasutaja loomiseks:
--
-- CREATE USER college_app WITH PASSWORD 'your_secure_password';
-- GRANT CONNECT ON DATABASE college_db TO college_app;
-- GRANT USAGE ON SCHEMA public TO college_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO college_app;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO college_app;
--
-- Then update backend/config.php to use this user instead of postgres:
-- Seejärel uuenda backend/config.php, et kasutada seda kasutajat postgres asemel:
--   DB_USER: 'college_app'
--   DB_PASS: 'your_secure_password'
-- ============================================================================
